'use client';

import { useState, useEffect } from 'react';

export default function DisclaimerModal() {
  const [open, setOpen] = useState(false);
  const [agreed, setAgreed] = useState(false);

  useEffect(() => {
    const hasAgreed = localStorage.getItem('klanko_disclaimer');
    if (!hasAgreed) setOpen(true);
  }, []);

  const handleAgree = () => {
    localStorage.setItem('klanko_disclaimer', 'true');
    setOpen(false);
  };

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-4">
      <div className="max-w-2xl w-full bg-panel border border-terminal-muted rounded-lg overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-terminal-muted flex items-center gap-3">
          <span className="text-terminal-amber text-xl">⚠</span>
          <h2 className="text-terminal-amber font-bold tracking-wider text-sm uppercase">
            Experimental Software — Please Read
          </h2>
        </div>

        {/* Content */}
        <div className="px-6 py-5 max-h-[60vh] overflow-y-auto space-y-4 text-sm text-neutral-300">
          <p className="text-neutral-400">
            Before you connect a wallet or interact with KLANKO, please read and acknowledge the following:
          </p>

          <ul className="space-y-2">
            {[
              'KLANKO is experimental software on Robinhood Chain mainnet.',
              'Nothing on this site is financial, investment, legal, or tax advice. This is Not Financial Advice (NFA).',
              'Crypto assets and tokens launched through this platform are highly volatile. Their value can fall to zero at any time.',
              'There is no guarantee of token drops, distributions, or any other outcome. Past activity is not a promise of future results.',
              'You are solely responsible for your own research, compliance with local laws, and any taxes owed.',
            ].map((item, i) => (
              <li key={i} className="flex gap-2">
                <span className="text-terminal-green">▸</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <p className="text-terminal-amber font-medium">
            Never invest, stake, or trade with more than you can afford to lose completely.
          </p>

          <div className="border-t border-terminal-muted pt-4">
            <h3 className="text-terminal-amber font-bold text-xs uppercase tracking-wider mb-2">
              Important — Not Corporate Dividends
            </h3>
            <ul className="space-y-2">
              {[
                '"Distributions" on this site is nomenclature only. These are NOT actual dividends and confer no equity, ownership, or shareholder rights. They are fees generated by protocol AMMs, distributed to NFTs activated within that AMM.',
                'This site is a UI and front end only. It allows interactions with permissionless smart contracts that are fully on chain.',
                'By using this protocol you agree that the use of these types of financial products is legal in your jurisdiction.',
              ].map((item, i) => (
                <li key={i} className="flex gap-2">
                  <span className="text-terminal-green">▸</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-terminal-muted">
          <label className="flex items-start gap-3 cursor-pointer mb-4">
            <input
              type="checkbox"
              checked={agreed}
              onChange={(e) => setAgreed(e.target.checked)}
              className="mt-1 w-4 h-4 accent-[#00ff88]"
            />
            <span className="text-xs text-neutral-400">
              I have read and understand this disclaimer. I acknowledge that KLANKO is experimental,
              that this is not financial advice, and that I may lose some or all of any funds I risk.
            </span>
          </label>
          <button
            onClick={handleAgree}
            disabled={!agreed}
            className="w-full py-3 rounded bg-terminal-green text-ink font-bold text-sm uppercase tracking-wider hover:bg-terminal-dim transition disabled:opacity-30 disabled:cursor-not-allowed"
          >
            I Understand &amp; Agree
          </button>
        </div>
      </div>
    </div>
  );
}
